# Importing the dependencies

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv(r"C:\Users\Harsh\Downloads\data_science01\dl_projects\task 1\Data\archive (20)\Training.csv")

In [3]:
df.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [4]:
df.tail()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  blackheads  scurring  skin_peeling  silver_like_dusting  \
4915  ...           0         0             0                    0   
4916  ...           1         1             0                    0   
4917  ...           0         0             0                    0   
4918  ...           0         0             1                    1   
4919  ...           0         0             0                    0   

      small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
4915                     0                   0        0                     0   
4916                     0                   0        0                     0   
4917                     0                   0        0                     0   
4918                     1                   1        0                     0   
4919                     0                   0        1                     1   

      yellow_crust_ooze                                prognosis  
4915                  0  (vertigo) Paroymsal  Positional Vertigo  
4916                  0                                     Acne  
4917                  0                  Urinary tract infection  
4918                  0                                Psoriasis  
4919                  1                                 Impetigo  

[5 rows x 133 columns]

In [5]:
df["prognosis"].nunique()

41

In [6]:
df.describe()

itching    skin_rash  nodal_skin_eruptions  continuous_sneezing  \
count  4920.000000  4920.000000           4920.000000          4920.000000   
mean      0.137805     0.159756              0.021951             0.045122   
std       0.344730     0.366417              0.146539             0.207593   
min       0.000000     0.000000              0.000000             0.000000   
25%       0.000000     0.000000              0.000000             0.000000   
50%       0.000000     0.000000              0.000000             0.000000   
75%       0.000000     0.000000              0.000000             0.000000   
max       1.000000     1.000000              1.000000             1.000000   

         shivering       chills   joint_pain  stomach_pain      acidity  \
count  4920.000000  4920.000000  4920.000000   4920.000000  4920.000000   
mean      0.021951     0.162195     0.139024      0.045122     0.045122   
std       0.146539     0.368667     0.346007      0.207593     0.207593   
min       0.000000     0.000000     0.000000      0.000000     0.000000   
25%       0.000000     0.000000     0.000000      0.000000     0.000000   
50%       0.000000     0.000000     0.000000      0.000000     0.000000   
75%       0.000000     0.000000     0.000000      0.000000     0.000000   
max       1.000000     1.000000     1.000000      1.000000     1.000000   

       ulcers_on_tongue  ...  pus_filled_pimples   blackheads     scurring  \
count       4920.000000  ...         4920.000000  4920.000000  4920.000000   
mean           0.021951  ...            0.021951     0.021951     0.021951   
std            0.146539  ...            0.146539     0.146539     0.146539   
min            0.000000  ...            0.000000     0.000000     0.000000   
25%            0.000000  ...            0.000000     0.000000     0.000000   
50%            0.000000  ...            0.000000     0.000000     0.000000   
75%            0.000000  ...            0.000000     0.000000     0.000000   
max            1.000000  ...            1.000000     1.000000     1.000000   

       skin_peeling  silver_like_dusting  small_dents_in_nails  \
count   4920.000000          4920.000000           4920.000000   
mean       0.023171             0.023171              0.023171   
std        0.150461             0.150461              0.150461   
min        0.000000             0.000000              0.000000   
25%        0.000000             0.000000              0.000000   
50%        0.000000             0.000000              0.000000   
75%        0.000000             0.000000              0.000000   
max        1.000000             1.000000              1.000000   

       inflammatory_nails      blister  red_sore_around_nose  \
count         4920.000000  4920.000000           4920.000000   
mean             0.023171     0.023171              0.023171   
std              0.150461     0.150461              0.150461   
min              0.000000     0.000000              0.000000   
25%              0.000000     0.000000              0.000000   
50%              0.000000     0.000000              0.000000   
75%              0.000000     0.000000              0.000000   
max              1.000000     1.000000              1.000000   

       yellow_crust_ooze  
count        4920.000000  
mean            0.023171  
std             0.150461  
min             0.000000  
25%             0.000000  
50%             0.000000  
75%             0.000000  
max             1.000000  

[8 rows x 132 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Columns: 133 entries, itching to prognosis
dtypes: int64(132), object(1)
memory usage: 5.0+ MB


In [8]:
df.isnull().sum()

itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
prognosis               0
Length: 133, dtype: int64

In [9]:
df.shape

(4920, 133)

In [10]:
X=df.drop("prognosis", axis=1)
y=df['prognosis']

In [11]:
y

0                              Fungal infection
1                              Fungal infection
2                              Fungal infection
3                              Fungal infection
4                              Fungal infection
                         ...                   
4915    (vertigo) Paroymsal  Positional Vertigo
4916                                       Acne
4917                    Urinary tract infection
4918                                  Psoriasis
4919                                   Impetigo
Name: prognosis, Length: 4920, dtype: object

In [12]:
X

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
0     ...                   0           0         0             0   
1     ...                   0           0         0             0   
2     ...                   0           0         0             0   
3     ...                   0           0         0             0   
4     ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
4915  ...                   0           0         0             0   
4916  ...                   1           1         1             0   
4917  ...                   0           0         0             0   
4918  ...                   0           0         0             1   
4919  ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
0                       0                     0                   0        0   
1                       0                     0                   0        0   
2                       0                     0                   0        0   
3                       0                     0                   0        0   
4                       0                     0                   0        0   
...                   ...                   ...                 ...      ...   
4915                    0                     0                   0        0   
4916                    0                     0                   0        0   
4917                    0                     0                   0        0   
4918                    1                     1                   1        0   
4919                    0                     0                   0        1   

      red_sore_around_nose  yellow_crust_ooze  
0                        0                  0  
1                        0                  0  
2                        0                  0  
3                        0                  0  
4                        0                  0  
...                    ...                ...  
4915                     0                  0  
4916              

In [13]:
for x in df.columns:
    if df[x].dtype == 'object':
        print(x)

prognosis


In [14]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

In [15]:
print(y)

[15 15 15 ... 38 35 27]


In [16]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [17]:
X_train.shape

(3936, 132)

In [18]:
X_test.shape

(984, 132)

In [19]:
y_train.shape

(3936,)

In [20]:
y_test.shape

(984,)

In [21]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report


# Initialize the Support Vector Classifier model
svc_model = SVC()

# Train the model on the training set
svc_model.fit(X_train, y_train)

# Make predictions on the training set
y_train_pred_svc = svc_model.predict(X_train)
# Make predictions on the testing set
y_test_pred_svc = svc_model.predict(X_test)

# Evaluate the model
print("Training Accuracy:", accuracy_score(y_train, y_train_pred_svc))
print("Testing Accuracy:", accuracy_score(y_test, y_test_pred_svc))

# Display confusion matrix and classification report for testing set
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_pred_svc))

print("\nClassification Report:")
print(classification_report(y_test, y_test_pred_svc))

Training Accuracy: 1.0
Testing Accuracy: 1.0

Confusion Matrix:
[[18  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  0 24 ...  0  0  0]
 ...
 [ 0  0  0 ... 26  0  0]
 [ 0  0  0 ...  0 22  0]
 [ 0  0  0 ...  0  0 34]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      1.00      1.00        30
           2       1.00      1.00      1.00        24
           3       1.00      1.00      1.00        25
           4       1.00      1.00      1.00        24
           5       1.00      1.00      1.00        23
           6       1.00      1.00      1.00        33
           7       1.00      1.00      1.00        23
           8       1.00      1.00      1.00        21
           9       1.00      1.00      1.00        15
          10       1.00      1.00      1.00        23
          11       1.00      1.00      1.00        26
          12       1.00      1.00      1.00        21

In [22]:
from joblib import dump
dump(svc_model, r'C:\\Users\\Harsh\\Downloads\\data_science01\\dl_projects\\task 1\\saved_model\\svc_model.joblib')


['C:\\\\Users\\\\Harsh\\\\Downloads\\\\data_science01\\\\dl_projects\\\\task 1\\\\saved_model\\\\svc_model.joblib']

In [23]:
from joblib import load

# Load the saved model
loaded_model = load(r'C:\\Users\\Harsh\\Downloads\\data_science01\\dl_projects\\task 1\\saved_model\\svc_model.joblib')

In [24]:
predictions = svc_model.predict(X_test)
for i in range(len(predictions)):
    print("Instance", i+1)
    print("Predicted Label:", predictions[i])
    print("Actual Label:", y_test[i])  # Accessing elements directly from NumPy array
    print()


Instance 1
Predicted Label: 2
Actual Label: 2

Instance 2
Predicted Label: 2
Actual Label: 2

Instance 3
Predicted Label: 24
Actual Label: 24

Instance 4
Predicted Label: 1
Actual Label: 1

Instance 5
Predicted Label: 9
Actual Label: 9

Instance 6
Predicted Label: 23
Actual Label: 23

Instance 7
Predicted Label: 25
Actual Label: 25

Instance 8
Predicted Label: 5
Actual Label: 5

Instance 9
Predicted Label: 19
Actual Label: 19

Instance 10
Predicted Label: 30
Actual Label: 30

Instance 11
Predicted Label: 38
Actual Label: 38

Instance 12
Predicted Label: 12
Actual Label: 12

Instance 13
Predicted Label: 21
Actual Label: 21

Instance 14
Predicted Label: 35
Actual Label: 35

Instance 15
Predicted Label: 3
Actual Label: 3

Instance 16
Predicted Label: 3
Actual Label: 3

Instance 17
Predicted Label: 13
Actual Label: 13

Instance 18
Predicted Label: 22
Actual Label: 22

Instance 19
Predicted Label: 12
Actual Label: 12

Instance 20
Predicted Label: 7
Actual Label: 7

Instance 21
Predicted Lab

In [25]:
symptoms_df=pd.read_csv(r"C:\Users\Harsh\Downloads\data_science01\dl_projects\task 1\Data\archive (20)\symtoms_df.csv")
precautions_df=pd.read_csv(r"C:\Users\Harsh\Downloads\data_science01\dl_projects\task 1\Data\archive (20)\precautions_df.csv")
workout_df=pd.read_csv(r"C:\Users\Harsh\Downloads\data_science01\dl_projects\task 1\Data\archive (20)\workout_df.csv")
description_df=pd.read_csv(r"C:\Users\Harsh\Downloads\data_science01\dl_projects\task 1\Data\archive (20)\description.csv")
diets_df=pd.read_csv(r"C:\Users\Harsh\Downloads\data_science01\dl_projects\task 1\Data\archive (20)\diets.csv")
medications_df=pd.read_csv(r"C:\Users\Harsh\Downloads\data_science01\dl_projects\task 1\Data\archive (20)\medications.csv")


In [26]:
def should_skip_first_column(df):
    # Check if the first column contains integers
    first_column = df.iloc[:, 0]
    return all(isinstance(value, int) for value in first_column)

# Initialize dictionaries
symptom_disease_map = {}
disease_symptom_map = {}
disease_precaution_map = {}
disease_description_map = {}
disease_workout_map = {}
disease_diet_map = {}
disease_medication_map = {}

# Determine whether to skip the first column
skip_first_column_symptoms = should_skip_first_column(symptoms_df)

# Iterate through each row in the symptoms DataFrame
for index, row in (symptoms_df.iloc[:, 1:].iterrows() if skip_first_column_symptoms else symptoms_df.iterrows()):
    disease = row['Disease']
    symptoms = [str(symptom) for symptom in row.drop('Disease').dropna().values if isinstance(symptom, str) and not any(char.isdigit() for char in symptom)]

    # Symptom to disease mapping
    for symptom in symptoms:
        if symptom not in symptom_disease_map:
            symptom_disease_map[symptom] = [disease]
        else:
            if disease not in symptom_disease_map[symptom]:
                symptom_disease_map[symptom].append(disease)

    # Disease to symptom mapping
    disease_symptom_map[disease] = symptoms

# Determine whether to skip the first column for precautions DataFrame
skip_first_column_precautions = should_skip_first_column(precautions_df)

# Iterate through each row in the precautions DataFrame
for index, row in (precautions_df.iloc[:, 1:].iterrows() if skip_first_column_precautions else precautions_df.iterrows()):
    disease = row['Disease']
    precautions = [precaution for precaution in row.drop('Disease').dropna().values]
    disease_precaution_map[disease] = precautions

# Iterate through each row in the description DataFrame
for index, row in description_df.iterrows():
    disease = row['Disease']
    description = row['Description']
    disease_description_map[disease] = description

# Iterate through each row in the workout DataFrame
for index, row in workout_df.iterrows():
    disease = row['Disease']
    workout = row['workout']
    disease_workout_map[disease] = workout

# Iterate through each row in the diets DataFrame
for index, row in diets_df.iterrows():
    disease = row['Disease']
    diet = row['Diet']
    disease_diet_map[disease] = diet

# Iterate through each row in the medications DataFrame
for index, row in medications_df.iterrows():
    disease = row['Disease']
    medication = row['Medication']
    disease_medication_map[disease] = medication

# Print disease, symptoms, precautions, descriptions, workouts, diets, and medications
for disease, symptoms in disease_symptom_map.items():
    print(f"Disease: {disease}")
    print("  Symptoms:")
    for symptom in symptoms:
        print(f"    - {symptom}")
    if disease in disease_precaution_map:
        print("  Precautions:")
        for precaution in disease_precaution_map[disease]:
            print(f"    - {precaution}")
    else:
        print("  No precautions available")
    if disease in disease_description_map:
        print(f"  Description: {disease_description_map[disease]}")
    if disease in disease_workout_map:
        print(f"  Workout: {disease_workout_map[disease]}")
    if disease in disease_diet_map:
        print(f"  Diet: {disease_diet_map[disease]}")
    if disease in disease_medication_map:
        print(f"  Medication: {disease_medication_map[disease]}")


Disease: Fungal infection
  Symptoms:
    - itching
    -  skin_rash
    -  nodal_skin_eruptions
    -  dischromic _patches
  Precautions:
    - bath twice
    - use detol or neem in bathing water
    - keep infected area dry
    - use clean cloths
  Description: Fungal infection is a common skin condition caused by fungi.
  Workout: Eat fruits and vegetables
  Diet: ['Antifungal Diet', 'Probiotics', 'Garlic', 'Coconut oil', 'Turmeric']
  Medication: ['Antifungal Cream', 'Fluconazole', 'Terbinafine', 'Clotrimazole', 'Ketoconazole']
Disease: Allergy
  Symptoms:
    -  continuous_sneezing
    -  shivering
    -  chills
    -  watering_from_eyes
  Precautions:
    - apply calamine
    - cover area with bandage
    - use ice to compress itching
  Description: Allergy is an immune system reaction to a substance in the environment.
  Workout: Avoid artificial additives
  Diet: ['Elimination Diet', 'Omega-3-rich foods', 'Vitamin C-rich foods', 'Quercetin-rich foods', 'Probiotics']
  Medicatio

In [ ]:
import tkinter as tk
from tkinter import messagebox
from fuzzywuzzy import process

# Function to match symptoms using fuzzy string matching
def match_symptoms(user_symptoms):
    matched_symptoms = set()
    for symptom in user_symptoms:
        matches = process.extract(symptom.lower(), symptom_disease_map.keys(), limit=5)
        for match, score in matches:
            if score >= 80:  
                matched_symptoms.add(match)
    return matched_symptoms

# Function to display disease information based on matched symptoms
def display_disease_info(symptoms):
    matched_diseases = set()
    for symptom in symptoms:
        if symptom in symptom_disease_map:
            matched_diseases.update(symptom_disease_map[symptom])

    if matched_diseases:
        for disease in matched_diseases:
            disease_info = f"Disease: {disease}\n"
            disease_info += "  Symptoms:\n"
            for symptom in disease_symptom_map[disease]:
                disease_info += f"    - {symptom}\n"
            if disease in disease_precaution_map:
                disease_info += "  Precautions:\n"
                for precaution in disease_precaution_map[disease]:
                    disease_info += f"    - {precaution}\n"
            else:
                disease_info += "  No precautions available\n"
            if disease in disease_description_map:
                disease_info += f"  Description: {disease_description_map[disease]}\n"
            if disease in disease_workout_map:
                disease_info += f"  Workout: {disease_workout_map[disease]}\n"
            if disease in disease_diet_map:
                disease_info += f"  Diet: {disease_diet_map[disease]}\n"
            if disease in disease_medication_map:
                disease_info += f"  Medication: {disease_medication_map[disease]}\n"
            messagebox.showinfo("Disease Information", disease_info)
    else:
        messagebox.showinfo("Disease Information", "No matching diseases found for the given symptoms.")

def on_submit():
    user_input = entry.get().strip().lower()
    user_symptoms = [symptom.strip() for symptom in user_input.split(',') if not symptom.isdigit()]
    matched_symptoms = match_symptoms(user_symptoms)
    display_disease_info(matched_symptoms)

# GUI Setup
root = tk.Tk()
root.title("Disease Information System")

label = tk.Label(root, text="Enter your symptoms (separated by commas):")
label.pack(pady=10)

entry = tk.Entry(root, width=50)
entry.pack(pady=5)

submit_button = tk.Button(root, text="Submit", command=on_submit)
submit_button.pack(pady=5)

root.mainloop()
